CREATE TABLE `jyl_word_processing` (
  `ID` varchar(50) CHARACTER SET utf8 NOT NULL,
  `SRCPATH` varchar(500) CHARACTER SET utf8 NOT NULL,
  `DESCPATH` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  `STATUS` varchar(500) CHARACTER SET utf8 DEFAULT NULL,
  `DATE` timestamp NULL DEFAULT NULL,
  `IDENTIFICATION` varchar(50) CHARACTER SET utf8 DEFAULT NULL,
  `TYPE` varchar(255) CHARACTER SET utf8 NOT NULL DEFAULT 'pdf',
  `EXTEND1` varchar(255) DEFAULT NULL,
  `EXTEND2` varchar(255) DEFAULT NULL,
  `EXTEND3` varchar(255) DEFAULT NULL,
  `EXTEND4` varchar(255) DEFAULT NULL,
  `EXTEND5` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `ID` (`ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

